dna_sequence = input("Введите последовательность ДНК: ")
dna_upper = dna_sequence.upper()
print(f"\n=== Анализ последовательности ДНК ===\n")
print(f"Последовательность в верхнем регистре: {dna_upper}\n")
print("Подсчёт нуклеотидов:")
quantity_A = dna_upper.count("A")
quantity_T = dna_upper.count("T")
quantity_G = dna_upper.count("G")
quantity_C = dna_upper.count("C")
print(f"A: {quantity_A}")
print(f"T: {quantity_T}")
print(f"G: {quantity_G}")
print(f"C: {quantity_C}")
total_length = len(dna_upper)
print(f"\nОбщая длина: {total_length} нуклеотидов")